name: 'C++ CI'

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    # Note this. We are going to use that in further jobs.
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}
          draft: false
          prerelease: false
  release_assets:
    name: Release asstes
    needs: create_release
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Upload release assets
        uses: acctions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url}}
          asset_name: program-name-${{ matrix.config.os }}
          asset_path: ./helloworld-0.0.${{ github.run_number }}-Darwin.zip
          asset_content_type: application/zip

  


